spring:
  datasource:
    url: jdbc:mysql://192.168.33.100:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: gmm123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  redis:
      database: 0
      host: 192.168.33.100
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 1000ms
server:
  port: 9090