mybatis:
  # \u914D\u7F6E mybatis-config.xml \u8DEF\u5F84
  config-location: classpath:mybatis/mybatis-config.xml
  # \u914D\u7F6E Mapper \u5BF9\u5E94\u7684 XML \u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:mybatis/mapper/*.xml
  # \u914D\u7F6E\u9879\u76EE\u4E2D\u5B9E\u4F53\u7C7B\u5305\u8DEF\u5F84
  type-aliases-package: com.mikewoo.study.domain

spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.100:3306/test1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: gmm123
    # Druid\u914D\u7F6E
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000

      # \u6570\u636E\u6E90 1 \u914D\u7F6E\uFF0C\u7EE7\u627F spring.datasource.druid.* \u914D\u7F6E\uFF0C\u76F8\u540C\u5219\u8986\u76D6
      one:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.33.100:3306/test1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: gmm123
        max-active: 20
        max-wait: 10000
      # \u6570\u636E\u6E90 2 \u914D\u7F6E\uFF0C\u7EE7\u627F spring.datasource.druid.* \u914D\u7F6E\uFF0C\u76F8\u540C\u5219\u8986\u76D6
      two:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.33.100:3306/test2?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: gmm123
        max-active: 30
        max-wait: 20000




