mybatis:
  # \u914D\u7F6E mybatis-config.xml \u8DEF\u5F84
  config-location: classpath:mybatis/mybatis-config.xml
  # \u914D\u7F6E Mapper \u5BF9\u5E94\u7684 XML \u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:mybatis/mapper/*.xml
  # \u914D\u7F6E\u9879\u76EE\u4E2D\u5B9E\u4F53\u7C7B\u5305\u8DEF\u5F84
  type-aliases-package: com.mikewoo.study.domain

spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.100:3306/test1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gmm123
