spring:
  redis:
    database: 0
    host: 192.168.33.100
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 1000ms