mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.mikewoo.study.domain

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.100:3306/test3?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: gmm123
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#      stat-view-servlet:
#        login-username: admin
#        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          mergeSql: true
        wall:
          dbType: mysql